set PKG_CONFIG_PATH=%LIBRARY_PREFIX%\lib\pkgconfig; 

mkdir build
cd build

# This is required to use proxsuite with Visual Studio 2019
# As soon as we swich to VS2022, we can drop this
set "CC=clang-cl.exe"
set "CXX=clang-cl.exe"

cmake ../^
    -GNinja^
    -DCMAKE_BUILD_TYPE=Release^
    -DCMAKE_PREFIX_PATH="%LIBRARY_PREFIX%"^
    -DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%"^
    -DINCLUDE_PREFIX:PATH=include^
    -DCMAKE_PREFIX:PATH=lib/cmake/casadi^
    -DLIB_PREFIX:PATH=lib^
    -DBIN_PREFIX:PATH=bin^
    -DWITH_SELFCONTAINED=OFF^
    -DWITH_PYTHON=ON^
    -DWITH_PYTHON3=ON^
    -DWITH_LAPACK=ON^
    -DWITH_IPOPT=ON^
    -DWITH_THREAD=ON^
    -DWITH_JSON=ON^
    -DWITH_OSQP=ON^
    -DWITH_BUILD_OSQP=OFF^
    -DWITH_QPOASES=ON^
    -DWITH_PROXQP=OFF^
    -DWITH_BUILD_PROXQP=OFF^
    -DWITH_TINYXML=ON^
    -DWITH_BUILD_TINYXML=OFF^
    -DSWIG_IMPORT=ON^
    -DWITH_KNITRO=ON^
    -DWITH_MOCKUP_KNITRO=ON^
    -DWITH_CPLEX=ON^
    -DWITH_MOCKUP_CPLEX=ON^
    -DWITH_GUROBI=ON^
    -DWITH_MOCKUP_GUROBI=ON^
    -DWITH_HSL=ON^
    -DWITH_MOCKUP_HSL=ON^
    -DWITH_WORHP=ON^
    -DWITH_MOCKUP_WORHP=ON^
    -DPYTHON_PREFIX=%SP_DIR%^
    -DWITH_COPYSIGN_UNDEF=ON^
    -DCASADI_PYTHON_PIP_METADATA_INSTALL=ON^
    -DCASADI_PYTHON_PIP_METADATA_INSTALLER:STRING="conda"

ninja install
