{% set name = "casadi" %}
{% set version = "3.4.0" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/casadi/casadi/archive/{{ version }}.tar.gz
  sha256: 400e7c5f512c59ac888fb1a1f95843007f8eb5ad1a6b2d2551573a2605fd5c14

build:
  number: 0
  skip: true  # [win]
  skip: true  # [np==111 and np==112]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - pkg-config  # [osx]
    - cmake
    - python
    - swig
    - numpy 1.11.*
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - ipopt

  run:
    - python
    - numpy >=1.11
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - ipopt

test:
  requires:
    - toolchain
  imports:
    - casadi
  files:
    - ipopt_nl.py
  commands:
    python ipopt_nl.py

about:
  home: http://casadi.org
  license: LGPL-3.0
  summary: 'CasADi is a symbolic framework for numeric optimization'

extra:
  recipe-maintainers:
    - pstjohn
