{% set name = "casadi" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/casadi/casadi/archive/{{ version }}.tar.gz
  sha256: 73eb096837bee2d1bbdfb8565f07c4a9d62b30cf831ad1ce3196df1f1770ae4d

build:
  number: 0
  skip: true  # [win]
  skip: true  # [np==111 and np==112]
  features:

requirements:
  build:
    - pkg-config  # [osx]
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - python
    - swig
    - numpy
    - ipopt

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - ipopt

test:
  imports:
    - casadi
  files:
    - ipopt_nl.py
  commands:
    python ipopt_nl.py

about:
  home: http://casadi.org
  license: LGPL-3.0
  summary: 'CasADi is a symbolic framework for numeric optimization'

extra:
  recipe-maintainers:
    - pstjohn
