{% set name = "casadi" %}
{% set version = "3.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/casadi/casadi/archive/{{ version }}.tar.gz
  sha256: 3b26e73ceb48cd9d713e3727e4038afa0e93471f014f8aaccdd77da382e2249a
  patches:
    - 2671.patch
    - 2878.patch

build:
  number: 9
  rpaths:
    - lib/
    - lib/{{ name }}/
  run_exports:
    - {{ pin_subpackage('casadi', max_pin='x.x') }}

requirements:
  build:
    - pkg-config
    - cmake
    - ninja
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - swig
  host:
    - libblas
    - libcblas
    - python
    - numpy
    - ipopt
    - libosqp

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - ipopt

test:
  imports:
    - casadi
  files:
    - ipopt_nl.py
  commands: 
    - python ipopt_nl.py
    - test $(pip list | grep casadi | tr -s " " | grep $PKG_VERSION | wc -l) -eq 1  # [unix]
  requires:
    - pip

about:
  home: http://casadi.org
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: CasADi is a symbolic framework for numeric optimization

extra:
  recipe-maintainers:
    - traversaro
    - pstjohn
    - pariterre
