{% set name = "casadi" %}
{% set version = "3.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/casadi/casadi/archive/{{ version }}.tar.gz
  sha256: 2732a90b49084c38c88e0fb59b49635456f6f19712436a64c998133e52fd396f

build:
  number: 1003
  skip: true  # [win]
  skip: true  # [np==111 and np==112]
  features:

requirements:
  build:
    - pkg-config  # [osx]
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - python
    - swig
    - numpy
    - ipopt

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - ipopt

test:
  imports:
    - casadi
  files:
    - ipopt_nl.py
  commands:
    python ipopt_nl.py

about:
  home: http://casadi.org
  license: LGPL-3.0
  summary: 'CasADi is a symbolic framework for numeric optimization'

extra:
  recipe-maintainers:
    - pstjohn
