{% set name = "casadi" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/casadi/casadi/archive/{{ version }}.tar.gz
  sha256: 73eb096837bee2d1bbdfb8565f07c4a9d62b30cf831ad1ce3196df1f1770ae4d

build:
  number: 4
  skip: True  # [win and vc<14]
  skip: True  # [py<35 or py>37]
  rpaths:
    - lib/
    - lib/{{ name }}/
  run_exports:
    - {{ pin_subpackage('casadi', max_pin='x.x') }}

requirements:
  build:
    - pkg-config
    - cmake
    - ninja
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - python
    - swig
    - numpy
    - ipopt

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - ipopt

test:
  imports:
    - casadi
  files:
    - ipopt_nl.py
  commands:
    python ipopt_nl.py

about:
  home: http://casadi.org
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: 'CasADi is a symbolic framework for numeric optimization'

extra:
  recipe-maintainers:
    - pstjohn
    - pariterre
