{% set name = "casadi" %}
{% set version = "3.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.zip
  url: https://github.com/casadi/casadi/releases/download/{{ version }}/casadi-source-v{{ version }}.zip
  sha256: 63d2c752d819f1790636f2015990c83bade6dd425af91b4239518312f6f6a052
  patches:
    - patches/2965.patch
    - patches/rtld_deepbind_null_environ_workaround.patch
    - patches/0001-Modernize-Python-find_package.patch
    - patches/0003-Bypass-CMake-crosscompiling-conda-forge-CI-issue.patch


build:
  number: 5
  rpaths:
    - lib/
    - lib/{{ name }}/
  run_exports:
    - {{ pin_subpackage('casadi', max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pkg-config
    - cmake
    - ninja
    - swig
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}  # [not win]
    - clang  # [win]
  host:
    - libblas
    - libcblas
    - liblapack
    - python
    - numpy
    - libosqp
    - proxsuite
    - tinyxml2
    - ipopt
    # libblasfeo is included as it is a public dependency of libfatrop
    - libblasfeo  # [unix]
    - libfatrop  # [unix]
  run:
    - python


test:
  imports:
    - casadi
  files:
    - ipopt_nl.py
  commands:
    - python ipopt_nl.py
    # Regression test for https://github.com/conda-forge/casadi-feedstock/issues/93
    - OMP_CANCELLATION=true OMP_PROC_BIND=true python ipopt_nl.py spral  # [linux]
    - test $(pip list | grep casadi | tr -s " " | grep $PKG_VERSION | wc -l) -eq 1  # [unix]
  requires:
    - pip

about:
  home: http://casadi.org
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: CasADi is a symbolic framework for numeric optimization

extra:
  recipe-maintainers:
    - agriyakhetarpal
    - traversaro
    - pstjohn
    - pariterre
