{% set name = "casadi" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.zip
  url: https://github.com/casadi/casadi/releases/download/{{ version }}/casadi-source-v{{ version }}.zip
  sha256: d04151f64c6a9d0a973821ff484ed8bf2ec79ea3a629e6371b0d6957bda2f55f
  patches:
    - 2906.patch
    - 2965.patch
    - 3077.patch
    - 3078.patch

build:
  number: 0
  rpaths:
    - lib/
    - lib/{{ name }}/
  run_exports:
    - {{ pin_subpackage('casadi', max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pkg-config
    - cmake
    - ninja
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - swig
  host:
    - libblas
    - libcblas
    - python
    - numpy
    - libosqp
    - eigen
    - tinyxml2
    - ipopt
  run:
    - python
    - {{ pin_compatible('numpy') }}


test:
  imports:
    - casadi
  files:
    - ipopt_nl.py
  commands: 
    - python ipopt_nl.py
    - test $(pip list | grep casadi | tr -s " " | grep $PKG_VERSION | wc -l) -eq 1  # [unix]
  requires:
    - pip

about:
  home: http://casadi.org
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: CasADi is a symbolic framework for numeric optimization

extra:
  recipe-maintainers:
    - traversaro
    - pstjohn
    - pariterre
