travis:
  secure:
    BINSTAR_TOKEN: nF5sJkEV0a47zqLCHxQvmWzlcZE9KMqsl4Yor0cVtlvvT1ENai4K93nfTi9ZnpKjCUl8lpkFaPatjwgLL+hhkqrq5UkHYmYBST+Q6lXbyIUFBhO5dRer1SdDVVOwAhjOf4fgfJ0ZMFDyssSE+pnQMp79fck6//x9Phbx/gNx3AsXJqCBrLgk2K4Eiymjkgpaynp7yoHZj9FSuhL7eKieAW9i8oxeAtdNusQYZ7Lo23Wg0dN4BBYNvHcYEBMZ8zA0b/O1NckFDTIfD7vJF2ewk9lztWm6mDShh7hrVkovoxeHU6IU8TuCYoaaJMb5CDOn5KjRZQg8VEM92Sn2Rs9hfDYAcpbwZjMaMm1dK9NBih+CDoTDSsuj4VC335kpRVmIi5WSeF7nJ43VMOuMwX8cyWvqM8MVup4IdrKaAtEdPCPFT90/74hFPf/zzsblvkwgWBCcjy4DHORniPUUqHkRA1q506UKhO5W8ij+SqZyN5Sb62J3jlsdc7RwAICa8UnBTsBG6TmuSazBq3PSApMz0bhAkd6stlFzziuQm5GSNNuEDq7wikM0oN/ZuZQ9xteYAQnMQC9NvfQmg/aV4CkLHxtV3i2VzzTmOgGon1UmyTVyXZEaF2qzFYemDcOAFkOjS/rTVHEBW49fU4QOXgAis4cvk588x/yaCF2DZhMJ33Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
