appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '38'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mOedoUeuEPXkGBC+wTbksKPKba+VDwf8V3z1R1vDbJRvLa40DIsdNWcfWI+v3QdC9f6CKuRVcqUWH4L1jz6YCzASiAALZ3RQTIvusjaHDqZH3EdXJHrKU+FFCdpcuGVLG4z1+pSzxQHtXQlZOGqNpK6ywywY3BxNigTFAAESlaMKmRKvxlDcVO9m1V10FbdVCQmM1aXzeB8J6UqW1h+vgFkq2rjmjHev9ORccffHzHNo3wnc3D/6w61l8j9VAk5WOnCHiv8W/IxjzTGyXdQMuUgZl+X7mBwIIZo2ZUENRWiDYOoIJwLbKfKmtf0ZyGxV2AEU9FlEgOYcRG1lk4ZkflrUPbJnLybgFIfzhjrbhJK89VEgHNmhiZRGWuenrwwhi0r39q8TeWTGzhqJIN3+1qWZGJ0WkSA7NGSnF1FOSgzta9C3ZhxxBmxeWP2x1jtqyfDXpD7mSW5hYUnIVk9ciz/9JJBD8jAdWM7g4LZ5jy8HknlZW7/1nXroilxDl686pJRZkQJdVmBlXEnnktXdWNEqrpOWnpj4JQNlqukuk0vgDkvkjOAY78e6IteS4WM/dXYdGHzRICwzVbFAOXqwzonDyo1FrOdJVz+IGxnbiVcYORvvd8tAPsmRLG1qLS6Jb1ejkTnDWVBNoz3un06JHNxKWvU+s3jTLWcKk1UUc/Y=}
